apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: wordcount-job
  namespace: default
spec:
  type: Python
  mode: cluster
  image: "spark-wordcount:1.0"
  imagePullPolicy: Never
  mainApplicationFile: "local:///app/wordcount.py"
  arguments:
    - "/app/input.txt"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0